[project]
name = "sql2mcp"
version = "0.1.0"
description = "Write SQL statements, get MCP Tools"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.9.2",
    "pugsql>=0.3.5",
]
